# Define a versão do Docker Compose
version: '3.8'

# Define os serviços (contêineres)
services:
  # Serviço da sua aplicação Python
  app:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: promove_api
    env_file:
      - .env
    ports:
      - "5001:8000"
    volumes:
      - .:/app
